# Generated by Django 2.1.7 on 2019-03-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_user',
            name='profile_user',
        ),
    ]
