# Generated by Django 2.1.7 on 2019-03-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
    ]
